### ISSUE TITLE
PSQL docker container loses all firepit data after down and up again

### ISSUE THREAD

**Issue by Berkan352** [IBM/firepit#129]
While using the firepit I face this issue:

When psql container is running there is no problem I can read and write data.
But when the container is down and up again the whole data is gone except schema and tables. 
So, the tables are there but there is no data inside.
And it happens only for the firepit tables the other tables are fine.

Here is the docker stack:

```
 pg:
    image: timescale/timescaledb:latest-pg14
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "${PGDB_PORT:-5432}:5432"
    networks:
      - network
```
Can you help with this issue?
